default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: support_act_development

test:
  <<: *default
  <% if ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL'] %>
  <% else %>
  database: support_act_test
  <% end %>

production:
  url: <%= ENV['DATABASE_URL'] %>
